INSERT INTO catalog_items VALUES (1, 1, 'C-001', '001', 'Revista Miscelánea', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (2, 1, 'C-001', '002', 'Noticiero', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (3, 1, 'C-001', '003', 'Entretenimiento', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (4, 1, 'C-001', '004', 'Programas Especiales', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (5, 1, 'C-001', '005', 'Deportivo', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (6, 1, 'C-001', '006', 'Revista Informativa', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (7, 2, 'C-002', '001', 'Informativo', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (8, 2, 'C-002', '002', 'Propaganda pagada', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (9, 3, 'C-003', '001', 'Tribunal Supremo de Justicia', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (10, 3, 'C-003', '002', 'Tribunal Agroambiental', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (11, 3, 'C-003', '003', 'Tribunal Constitucional Plurinacional', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (12, 3, 'C-003', '004', 'Consejo de la Magistratura', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (13, 4, 'C-004', '001', 'Español', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (14, 4, 'C-004', '002', 'Quechua', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (15, 4, 'C-004', '003', 'Aymara', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (16, 5, 'C-005', '001', 'Candidato/a', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (17, 5, 'C-005', '002', 'Medio de comunicación', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (18, 5, 'C-005', '003', 'Persona individual o colectiva, organización social, colegiada o política', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (19, 5, 'C-005', '004', 'Servidores públicos', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (20, 6, 'C-006', '001', 'Solicitar el voto por su candidatura u otras', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (21, 6, 'C-006', '002', 'Emitir opinión en contra de otras candidaturas', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (22, 6, 'C-006', '003', 'Dirigir o conducir programas en medios de comunicación', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (23, 6, 'C-006', '004', 'Contratar espacios pagados en medios de comunicación para la promoción de su candidatura', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (24, 6, 'C-006', '005', 'Participar en reuniones públicas, mitines, asambleas, cabildos, marchas, caminatas, concentraciones y otras expresiones públicas', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (25, 6, 'C-006', '006', 'Hacer uso de la papeleta de votación en materiales de difusión de medios', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (26, 6, 'C-006', '007', 'Usar distintivos o alguna numeración que indique su ubicación en la papeleta electoral asi como de cualquier símbolo patrio y/o religioso', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (27, 6, 'C-006', '008', 'Solicitar de manera directa o indirecta que servidores públicos realicen propaganda por su respectiva candidatura', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (28, 7, 'C-007', '001', 'Solicitar el voto ciudadano para alguna candidatura o candidaturas en cualquiera de sus espacios', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (29, 7, 'C-007', '002', 'Difundir resultados de estudios de opinión en material electoral que hubiese sido realizados fuera del plazo establecido, sin cumplir los requisitos técnicos o por empresas o instituciones no habilitadas', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (30, 7, 'C-007', '003', 'Aceptar contratos con la finalidad de difundir méritos de las candidaturas y los candidatos, a excepción de los efectuados por el Órgano Electoral Plurinacional', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (31, 8, 'C-008', '001', 'Información', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (32, 8, 'C-008', '002', 'Opinión', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (33, 8, 'C-008', '003', 'Entrevista', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (34, 8, 'C-008', '004', 'Propaganda', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (35, 9, 'C-009', '001', 'Facebook', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (36, 9, 'C-009', '002', 'Youtube', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (37, 9, 'C-009', '003', 'X (Twitter)', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (38, 9, 'C-009', '004', 'Instagram', NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO catalog_items VALUES (39, 9, 'C-009', '005', 'TikTok', NULL, true, NULL, NULL, NULL, NULL, NULL);