<?php

namespace App\Containers\AppSection\ActivityLog\Constants;

class LogConstants
{
    public const LOGIN_ADMIN = 'LOGIN_ADMIN';

    public const CREATE_DYNAMIC_FORM = 'CREATE_DYNAMIC_FORM';
    public const ADD_FORM_FIELD = 'ADD_FORM_FIELD';
    public const DELETE_FORM_FIELD = 'DELETE_FORM_FIELD';

    public const CREATED_USER = 'CREATED_USER';
    public const UPDATED_USER_DATA_PASSWORD = 'UPDATED_USER_DATA_PASSWORD';

    public const CREATED_ELECTION = 'CREATED_ELECTION';
    public const UPDATED_ELECTION = 'UPDATED_ELECTION';
    public const UPDATED_STATUS_ELECTION = 'UPDATED_STATUS_ELECTION';

    public const CREATED_POLITICAL_GROUP = 'CREATED_POLITICAL_GROUP';
    public const UPDATED_POLITICAL_GROUP = 'UPDATED_POLITICAL_GROUP';
    public const REGISTERED_POLITICAL_GROUP = 'REGISTERED_POLITICAL_GROUP';

    public const CREATED_ACCREDITATION = 'CREATED_ACCREDITATION';
    public const UPDATED_ACCREDITATION = 'UPDATED_ACCREDITATION';
    public const SUBMITTED_ACCREDITATION = 'SUBMITTED_ACCREDITATION';
    public const STATUS_UPDATED_ACCREDITATION = 'STATUS_UPDATED_ACCREDITATION';

    public const CREATED_MONITORING = 'CREATED_MONITORING';
    public const UPDATED_MONITORING = 'UPDATED_MONITORING';
    public const SUBMIT_MONITORING_TO_REPORT = 'SUBMIT_MONITORING_TO_REPORT';

    public const CREATE_ANALYSIS_REPORT = 'CREATE_ANALYSIS_REPORT';
    public const SUBMIT_ANALYSIS_TO_SECRETARIAT = 'SUBMIT_ANALYSIS_TO_SECRETARIAT';
    public const SUBMIT_ANALYSIS_TO_PLENARY = 'SUBMIT_ANALYSIS_TO_PLENARY';

    public const ENABLED_USER_MEDIA_ACCOUNT = 'ENABLED_USER_MEDIA_ACCOUNT';
    public const ENABLED_USER_POLITICAL_ACCOUNT = 'ENABLED_USER_POLITICAL_ACCOUNT';

}
