<?php
namespace App\Containers\AppSection\ActivityLog\Constants;

class LogConstants {
    const ENABLED_USER_MEDIA_ACCOUNT = 'ENABLED_USER_MEDIA_ACCOUNT';
    const SUBMIT_MONITORING_TO_REPORT = 'SUBMIT_MONITORING_TO_REPORT';
    const CREATE_ANALYSIS_REPORT = 'CREATE_ANALYSIS_REPORT';
    const SUBMIT_ANALYSIS_TO_SECRETARIAT = 'SUBMIT_ANALYSIS_TO_SECRETARIAT';
    const SUBMIT_ANALYSIS_TO_PLENARY = 'SUBMIT_ANALYSIS_TO_PLENARY';

}