<?php
namespace App\Containers\AppSection\ActivityLog\Constants;

class LogConstants {

    const LOGIN_ADMIN = 'LOGIN_ADMIN';

    const CREATE_DYNAMIC_FORM = 'CREATE_DYNAMIC_FORM';
    const ADD_FORM_FIELD = 'ADD_FORM_FIELD';
    const DELETE_FORM_FIELD = 'DELETE_FORM_FIELD';

    const CREATED_USER = 'CREATED_USER';
    const UPDATED_USER_DATA_PASSWORD = 'UPDATED_USER_DATA_PASSWORD';

    const CREATED_ELECTION = 'CREATED_ELECTION';
    const UPDATED_ELECTION = 'UPDATED_ELECTION';
    const UPDATED_STATUS_ELECTION = 'UPDATED_STATUS_ELECTION';

    const CREATED_POLITICAL_GROUP = 'CREATED_POLITICAL_GROUP';
    const UPDATED_POLITICAL_GROUP = 'UPDATED_POLITICAL_GROUP';
    const REGISTERED_POLITICAL_GROUP = 'REGISTERED_POLITICAL_GROUP';

    const ENABLED_USER_MEDIA_ACCOUNT = 'ENABLED_USER_MEDIA_ACCOUNT';
    const ENABLED_USER_POLITICAL_ACCOUNT = 'ENABLED_USER_POLITICAL_ACCOUNT';
    const SUBMIT_MONITORING_TO_REPORT = 'SUBMIT_MONITORING_TO_REPORT';
    const CREATE_ANALYSIS_REPORT = 'CREATE_ANALYSIS_REPORT';
    const SUBMIT_ANALYSIS_TO_SECRETARIAT = 'SUBMIT_ANALYSIS_TO_SECRETARIAT';
    const SUBMIT_ANALYSIS_TO_PLENARY = 'SUBMIT_ANALYSIS_TO_PLENARY';

}